### ISSUE TITLE
why do you use Keycloak

### ISSUE THREAD

**Issue by HelloTo4x** [SttDmitry/keycloak#1]
Hi, can u tell me why u use Keycloak instead of Spring security, which feature does it have but Spring security doesn't have it ?

**Comment by HelloTo4x** [comment]
you mean it is a web interface, and don't need to use SQL, right ?

**Comment by SttDmitry** [comment]
Yeah, if you look into docker-compose file - i'm trying to run it on port 8484 and then can log in as an admin. Then set up environment such as realm, client, roles and user. All of it doesn't require you to know any SQL, because it's automatic in docker image

**Comment by HelloTo4x** [comment]
u mean like :https://github.com/SttDmitry/keycloak/blob/master/src/main/resources/docker-compose.yml

**Comment by HelloTo4x** [comment]
sure, thank u <3 have a nice day
